// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package maintenance

import (
	"xiao-yi-transit/api/maintenance"
)

var (
	// Controller is the controller instance.
	Controller = controllerNew()
)

// controllerNew creates and returns a new controller object.
func controllerNew() *controllerV1 {
	return &controllerV1{}
}

// controllerV1 is the controller for version 1.
type controllerV1 struct{}

// V1 returns the controller of version 1.
func (c *controllerV1) V1() maintenance.IMaintenanceV1 {
	return NewV1()
}
