// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package vehicle

import (
	"xiao-yi-transit/api/vehicle"
)

type ControllerV1 struct{}

func NewV1() vehicle.IVehicleV1 {
	return &ControllerV1{}
}
