// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package station

import (
	"xiao-yi-transit/api/station"
)

type ControllerV1 struct{}

func NewV1() station.IStationV1 {
	return &ControllerV1{}
}
