
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:xiao-yi-transit:xiao-yi-transit@tcp(127.0.0.1:3306)/xiao-yi-transit"
        descriptionTag: true
        jsonCase:  "Snake"
        removePrefix: "xf_"
        gJsonSupport: true
  build:
    name:     "XiaoYiTransit"
    arch:     "amd64,arm64,arm"
    system:   "linux,darwin,windows"
    mod:      "none"
    version:  "v1.0.0"
    path:   "./dist"
    extra:    ""
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app