# https://goframe.org/docs/web/server-config-file-template
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level: "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    host: "localhost"
    port: "3306"
    user: "xiao-yi-transit"
    pass: "xiao-yi-transit"
    name: "xiao-yi-transit"
    type: "mysql"