// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// driverShiftDao is the data access object for the table xf_driver_shift.
// You can define custom methods on it to extend its functionality as needed.
type driverShiftDao struct {
	*internal.DriverShiftDao
}

var (
	// DriverShift is a globally accessible object for table xf_driver_shift operations.
	DriverShift = driverShiftDao{internal.NewDriverShiftDao()}
)

// Add your custom methods and functionality below.
