// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// driverDao is the data access object for the table xf_driver.
// You can define custom methods on it to extend its functionality as needed.
type driverDao struct {
	*internal.DriverDao
}

var (
	// Driver is a globally accessible object for table xf_driver operations.
	Driver = driverDao{internal.NewDriverDao()}
)

// Add your custom methods and functionality below.
