// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// maintenanceItemDao is the data access object for the table xf_maintenance_item.
// You can define custom methods on it to extend its functionality as needed.
type maintenanceItemDao struct {
	*internal.MaintenanceItemDao
}

var (
	// MaintenanceItem is a globally accessible object for table xf_maintenance_item operations.
	MaintenanceItem = maintenanceItemDao{internal.NewMaintenanceItemDao()}
)

// Add your custom methods and functionality below.
