// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// maintenanceDao is the data access object for the table xf_maintenance.
// You can define custom methods on it to extend its functionality as needed.
type maintenanceDao struct {
	*internal.MaintenanceDao
}

var (
	// Maintenance is a globally accessible object for table xf_maintenance operations.
	Maintenance = maintenanceDao{internal.NewMaintenanceDao()}
)

// Add your custom methods and functionality below.
