// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// routeStationDao is the data access object for the table xf_route_station.
// You can define custom methods on it to extend its functionality as needed.
type routeStationDao struct {
	*internal.RouteStationDao
}

var (
	// RouteStation is a globally accessible object for table xf_route_station operations.
	RouteStation = routeStationDao{internal.NewRouteStationDao()}
)

// Add your custom methods and functionality below.
