// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// routeDao is the data access object for the table xf_route.
// You can define custom methods on it to extend its functionality as needed.
type routeDao struct {
	*internal.RouteDao
}

var (
	// Route is a globally accessible object for table xf_route operations.
	Route = routeDao{internal.NewRouteDao()}
)

// Add your custom methods and functionality below.
