// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// scheduleTemplateDao is the data access object for the table xf_schedule_template.
// You can define custom methods on it to extend its functionality as needed.
type scheduleTemplateDao struct {
	*internal.ScheduleTemplateDao
}

var (
	// ScheduleTemplate is a globally accessible object for table xf_schedule_template operations.
	ScheduleTemplate = scheduleTemplateDao{internal.NewScheduleTemplateDao()}
)

// Add your custom methods and functionality below.
