// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// scheduleDao is the data access object for the table xf_schedule.
// You can define custom methods on it to extend its functionality as needed.
type scheduleDao struct {
	*internal.ScheduleDao
}

var (
	// Schedule is a globally accessible object for table xf_schedule operations.
	Schedule = scheduleDao{internal.NewScheduleDao()}
)

// Add your custom methods and functionality below.
