// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// stationDao is the data access object for the table xf_station.
// You can define custom methods on it to extend its functionality as needed.
type stationDao struct {
	*internal.StationDao
}

var (
	// Station is a globally accessible object for table xf_station operations.
	Station = stationDao{internal.NewStationDao()}
)

// Add your custom methods and functionality below.
