// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// userTokenDao is the data access object for the table xf_user_token.
// You can define custom methods on it to extend its functionality as needed.
type userTokenDao struct {
	*internal.UserTokenDao
}

var (
	// UserToken is a globally accessible object for table xf_user_token operations.
	UserToken = userTokenDao{internal.NewUserTokenDao()}
)

// Add your custom methods and functionality below.
