// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// vehicleDao is the data access object for the table xf_vehicle.
// You can define custom methods on it to extend its functionality as needed.
type vehicleDao struct {
	*internal.VehicleDao
}

var (
	// Vehicle is a globally accessible object for table xf_vehicle operations.
	Vehicle = vehicleDao{internal.NewVehicleDao()}
)

// Add your custom methods and functionality below.
