// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// vehicleInsuranceDao is the data access object for the table xf_vehicle_insurance.
// You can define custom methods on it to extend its functionality as needed.
type vehicleInsuranceDao struct {
	*internal.VehicleInsuranceDao
}

var (
	// VehicleInsurance is a globally accessible object for table xf_vehicle_insurance operations.
	VehicleInsurance = vehicleInsuranceDao{internal.NewVehicleInsuranceDao()}
)

// Add your custom methods and functionality below.