// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// vehicleInspectionDao is the data access object for the table xf_vehicle_inspection.
// You can define custom methods on it to extend its functionality as needed.
type vehicleInspectionDao struct {
	*internal.VehicleInspectionDao
}

var (
	// VehicleInspection is a globally accessible object for table xf_vehicle_inspection operations.
	VehicleInspection = vehicleInspectionDao{internal.NewVehicleInspectionDao()}
)

// Add your custom methods and functionality below.
