// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiao-yi-transit/internal/dao/internal"
)

// vehicleFaultDao is the data access object for the table xf_vehicle_fault.
// You can define custom methods on it to extend its functionality as needed.
type vehicleFaultDao struct {
	*internal.VehicleFaultDao
}

var (
	// VehicleFault is a globally accessible object for table xf_vehicle_fault operations.
	VehicleFault = vehicleFaultDao{internal.NewVehicleFaultDao()}
)

// Add your custom methods and functionality below.
