// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package driver

import (
	"xiao-yi-transit/api/driver"
)

type ControllerV1 struct{}

func NewV1() driver.IDriverV1 {
	return &ControllerV1{}
}